- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: Install ntpdate
    ansible.builtin.package:
      name: ntpdate
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started