- name: variables from PLAY1
  hosts: localhost
  vars: 
    Course: "Devops"
    Trainer: "SIVA"
    Duration: "3 months"
  tasks: 
  - name: writing variables
    ansible.builtin.debug:
      msg: "hi i am learning {{Course}} engineering , trainer is {{Trainer}}, duration is {{Duration}}"