- name: variables from PLAY1
  hosts: localhost
  vars: 
    course: "Devops"
    trainer: "siva"
    duration: "3months"
  tasks: 
  - name: writing variables
    ansible.builtin.debug:
      msg: "Hi, i am learning {{course}}, trainer is {{trainer}}, duration is {{duration}} "