- name: condition
  hosts: localhost
  tasks:
  - name: check roboshop user exit or not
    ansible.builtin.command: id roboshop
    register: user
  
  - name: print the user variable
    ansible.builtin.debug: 
      msg: "user output is: {{user}}"
  
  - name: print return code or exit status
    ansible.builtin.debug:
      msg: "status is: {{user.rc}}"
  
  - name: create user
    ansible.builtin.user:
      name: roboshop
    when: user.rc != 0